### ISSUE TITLE
Sidebar styling changes

### ISSUE THREAD

**Issue by ScottHarrisonDev** [ScottHarrisonDev/playlist-curator#2]
The sidebar (selector `aside`) which contains the New Playlist songs should be hidden until the user adds their first song. Once this song has been added (`playlist.tracks.length` is greater than 0) the sidebar should slide into view from the right.

Here is the sidebar in it's current (empty) form:
<img width="454" alt="screen shot 2018-10-03 at 23 55 28" src="https://user-images.githubusercontent.com/7291764/46443998-d9891a00-c767-11e8-9544-acfdc524ea0d.png">

**Comment by klauskpm** [comment]
Can I take this?

**Comment by shad-k** [comment]
@ScottHarrisonDev I'd like to work on this. Will make a PR soon.
