### ISSUE TITLE
Song titles wrapping

### ISSUE THREAD

**Issue by ScottHarrisonDev** [ScottHarrisonDev/playlist-curator#3]
The song titles in the search results are wrapping if they have a long name. Not sure what best solution would be, truncate the song name or allow it to wrap. 

Here is an example of what needs to be fixed:
<img width="752" alt="screen shot 2018-10-03 at 23 56 49" src="https://user-images.githubusercontent.com/7291764/46444060-27058700-c768-11e8-9003-72258660fb4f.png">

**Comment by asfo** [comment]
I'll take this! °U°/
